# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created: Mon Jan 30 23:08:50 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(439, 581)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, 10, 431, 591))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtGui.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(40, 10, 361, 71))
        self.lineEdit.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit.setObjectName("lineEdit")
        self.lcdNumber = QtGui.QLCDNumber(self.frame)
        self.lcdNumber.setGeometry(QtCore.QRect(40, 100, 361, 71))
        self.lcdNumber.setObjectName("lcdNumber")
        self.tabWidget = QtGui.QTabWidget(self.frame)
        self.tabWidget.setGeometry(QtCore.QRect(30, 180, 401, 351))
        self.tabWidget.setObjectName("tabWidget")
        self.Standard = QtGui.QWidget()
        self.Standard.setObjectName("Standard")
        self.pClear = QtGui.QPushButton(self.Standard)
        self.pClear.setGeometry(QtCore.QRect(11, 30, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pClear.setFont(font)
        self.pClear.setAutoFillBackground(False)
        self.pClear.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pClear.setObjectName("pClear")
        self.pBackspace = QtGui.QPushButton(self.Standard)
        self.pBackspace.setGeometry(QtCore.QRect(202, 30, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pBackspace.setFont(font)
        self.pBackspace.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pBackspace.setObjectName("pBackspace")
        self.layoutWidget = QtGui.QWidget(self.Standard)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 80, 371, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.p2 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p2.sizePolicy().hasHeightForWidth())
        self.p2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.p2.setFont(font)
        self.p2.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.p2.setObjectName("p2")
        self.gridLayout_2.addWidget(self.p2, 2, 1, 1, 1)
        self.p1 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p1.sizePolicy().hasHeightForWidth())
        self.p1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.p1.setFont(font)
        self.p1.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.p1.setObjectName("p1")
        self.gridLayout_2.addWidget(self.p1, 2, 0, 1, 1)
        self.p3 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p3.sizePolicy().hasHeightForWidth())
        self.p3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.p3.setFont(font)
        self.p3.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.p3.setObjectName("p3")
        self.gridLayout_2.addWidget(self.p3, 2, 2, 1, 1)
        self.pSubstract = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pSubstract.sizePolicy().hasHeightForWidth())
        self.pSubstract.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pSubstract.setFont(font)
        self.pSubstract.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pSubstract.setObjectName("pSubstract")
        self.gridLayout_2.addWidget(self.pSubstract, 2, 3, 1, 1)
        self.p9 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p9.sizePolicy().hasHeightForWidth())
        self.p9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.p9.setFont(font)
        self.p9.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.p9.setObjectName("p9")
        self.gridLayout_2.addWidget(self.p9, 0, 2, 1, 1)
        self.p4 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p4.sizePolicy().hasHeightForWidth())
        self.p4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.p4.setFont(font)
        self.p4.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.p4.setObjectName("p4")
        self.gridLayout_2.addWidget(self.p4, 1, 0, 1, 1)
        self.p7 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p7.sizePolicy().hasHeightForWidth())
        self.p7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.p7.setFont(font)
        self.p7.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.p7.setObjectName("p7")
        self.gridLayout_2.addWidget(self.p7, 0, 0, 1, 1)
        self.p5 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p5.sizePolicy().hasHeightForWidth())
        self.p5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.p5.setFont(font)
        self.p5.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.p5.setObjectName("p5")
        self.gridLayout_2.addWidget(self.p5, 1, 1, 1, 1)
        self.pDivision = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pDivision.sizePolicy().hasHeightForWidth())
        self.pDivision.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pDivision.setFont(font)
        self.pDivision.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pDivision.setObjectName("pDivision")
        self.gridLayout_2.addWidget(self.pDivision, 0, 3, 1, 1)
        self.pMultiply = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pMultiply.sizePolicy().hasHeightForWidth())
        self.pMultiply.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pMultiply.setFont(font)
        self.pMultiply.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pMultiply.setObjectName("pMultiply")
        self.gridLayout_2.addWidget(self.pMultiply, 1, 3, 1, 1)
        self.pDot = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pDot.sizePolicy().hasHeightForWidth())
        self.pDot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pDot.setFont(font)
        self.pDot.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pDot.setObjectName("pDot")
        self.gridLayout_2.addWidget(self.pDot, 3, 0, 1, 1)
        self.pAdd = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pAdd.sizePolicy().hasHeightForWidth())
        self.pAdd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pAdd.setFont(font)
        self.pAdd.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pAdd.setObjectName("pAdd")
        self.gridLayout_2.addWidget(self.pAdd, 3, 3, 1, 1)
        self.p0 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p0.sizePolicy().hasHeightForWidth())
        self.p0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.p0.setFont(font)
        self.p0.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.p0.setObjectName("p0")
        self.gridLayout_2.addWidget(self.p0, 3, 1, 1, 1)
        self.pEqualTo = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pEqualTo.sizePolicy().hasHeightForWidth())
        self.pEqualTo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pEqualTo.setFont(font)
        self.pEqualTo.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pEqualTo.setObjectName("pEqualTo")
        self.gridLayout_2.addWidget(self.pEqualTo, 3, 2, 1, 1)
        self.p8 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p8.sizePolicy().hasHeightForWidth())
        self.p8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.p8.setFont(font)
        self.p8.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.p8.setObjectName("p8")
        self.gridLayout_2.addWidget(self.p8, 0, 1, 1, 1)
        self.p6 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p6.sizePolicy().hasHeightForWidth())
        self.p6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.p6.setFont(font)
        self.p6.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.p6.setObjectName("p6")
        self.gridLayout_2.addWidget(self.p6, 1, 2, 1, 1)
        self.pOpenParenthesis2 = QtGui.QPushButton(self.Standard)
        self.pOpenParenthesis2.setGeometry(QtCore.QRect(10, 260, 181, 38))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pOpenParenthesis2.sizePolicy().hasHeightForWidth())
        self.pOpenParenthesis2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pOpenParenthesis2.setFont(font)
        self.pOpenParenthesis2.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pOpenParenthesis2.setObjectName("pOpenParenthesis2")
        self.pCloseParenthesis2 = QtGui.QPushButton(self.Standard)
        self.pCloseParenthesis2.setGeometry(QtCore.QRect(199, 260, 181, 38))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pCloseParenthesis2.sizePolicy().hasHeightForWidth())
        self.pCloseParenthesis2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pCloseParenthesis2.setFont(font)
        self.pCloseParenthesis2.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pCloseParenthesis2.setObjectName("pCloseParenthesis2")
        self.tabWidget.addTab(self.Standard, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtGui.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.pATan = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pATan.sizePolicy().hasHeightForWidth())
        self.pATan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pATan.setFont(font)
        self.pATan.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pATan.setObjectName("pATan")
        self.gridLayout.addWidget(self.pATan, 2, 2, 1, 1)
        self.pFact = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pFact.sizePolicy().hasHeightForWidth())
        self.pFact.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pFact.setFont(font)
        self.pFact.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pFact.setObjectName("pFact")
        self.gridLayout.addWidget(self.pFact, 4, 3, 1, 1)
        self.pTan = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pTan.sizePolicy().hasHeightForWidth())
        self.pTan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pTan.setFont(font)
        self.pTan.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pTan.setObjectName("pTan")
        self.gridLayout.addWidget(self.pTan, 1, 2, 1, 1)
        self.pCloseParenthesis = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pCloseParenthesis.sizePolicy().hasHeightForWidth())
        self.pCloseParenthesis.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pCloseParenthesis.setFont(font)
        self.pCloseParenthesis.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pCloseParenthesis.setObjectName("pCloseParenthesis")
        self.gridLayout.addWidget(self.pCloseParenthesis, 5, 1, 1, 1)
        self.pCosh = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pCosh.sizePolicy().hasHeightForWidth())
        self.pCosh.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pCosh.setFont(font)
        self.pCosh.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pCosh.setObjectName("pCosh")
        self.gridLayout.addWidget(self.pCosh, 3, 1, 1, 1)
        self.pNaturalLog = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pNaturalLog.sizePolicy().hasHeightForWidth())
        self.pNaturalLog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pNaturalLog.setFont(font)
        self.pNaturalLog.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pNaturalLog.setObjectName("pNaturalLog")
        self.gridLayout.addWidget(self.pNaturalLog, 4, 0, 1, 1)
        self.pASin = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pASin.sizePolicy().hasHeightForWidth())
        self.pASin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pASin.setFont(font)
        self.pASin.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pASin.setObjectName("pASin")
        self.gridLayout.addWidget(self.pASin, 2, 0, 1, 1)
        self.pFloor = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pFloor.sizePolicy().hasHeightForWidth())
        self.pFloor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pFloor.setFont(font)
        self.pFloor.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pFloor.setObjectName("pFloor")
        self.gridLayout.addWidget(self.pFloor, 5, 2, 1, 1)
        self.pEqualTo2 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pEqualTo2.sizePolicy().hasHeightForWidth())
        self.pEqualTo2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.pEqualTo2.setFont(font)
        self.pEqualTo2.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pEqualTo2.setObjectName("pEqualTo2")
        self.gridLayout.addWidget(self.pEqualTo2, 6, 3, 1, 1)
        self.pLog = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pLog.sizePolicy().hasHeightForWidth())
        self.pLog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pLog.setFont(font)
        self.pLog.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pLog.setObjectName("pLog")
        self.gridLayout.addWidget(self.pLog, 4, 1, 1, 1)
        self.pPI = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pPI.sizePolicy().hasHeightForWidth())
        self.pPI.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pPI.setFont(font)
        self.pPI.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pPI.setObjectName("pPI")
        self.gridLayout.addWidget(self.pPI, 1, 3, 1, 1)
        self.pClear2 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pClear2.sizePolicy().hasHeightForWidth())
        self.pClear2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pClear2.setFont(font)
        self.pClear2.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pClear2.setObjectName("pClear2")
        self.gridLayout.addWidget(self.pClear2, 0, 0, 1, 2)
        self.pSinh = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pSinh.sizePolicy().hasHeightForWidth())
        self.pSinh.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pSinh.setFont(font)
        self.pSinh.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pSinh.setObjectName("pSinh")
        self.gridLayout.addWidget(self.pSinh, 3, 0, 1, 1)
        self.pMod = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pMod.sizePolicy().hasHeightForWidth())
        self.pMod.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.pMod.setFont(font)
        self.pMod.setStyleSheet("background-color: rgb(107, 255, 107);\n"
"")
        self.pMod.setObjectName("pMod")
        self.gridLayout.addWidget(self.pMod, 6, 0, 1, 1)
        self.pRem = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pRem.sizePolicy().hasHeightForWidth())
        self.pRem.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.pRem.setFont(font)
        self.pRem.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pRem.setObjectName("pRem")
        self.gridLayout.addWidget(self.pRem, 6, 2, 1, 1)
        self.pOpenParenthesis = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pOpenParenthesis.sizePolicy().hasHeightForWidth())
        self.pOpenParenthesis.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pOpenParenthesis.setFont(font)
        self.pOpenParenthesis.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pOpenParenthesis.setObjectName("pOpenParenthesis")
        self.gridLayout.addWidget(self.pOpenParenthesis, 5, 0, 1, 1)
        self.pAbs = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pAbs.sizePolicy().hasHeightForWidth())
        self.pAbs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.pAbs.setFont(font)
        self.pAbs.setStyleSheet("background-color: rgb(107, 255, 107);\n"
"\n"
"")
        self.pAbs.setObjectName("pAbs")
        self.gridLayout.addWidget(self.pAbs, 6, 1, 1, 1)
        self.pTanh = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pTanh.sizePolicy().hasHeightForWidth())
        self.pTanh.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pTanh.setFont(font)
        self.pTanh.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pTanh.setObjectName("pTanh")
        self.gridLayout.addWidget(self.pTanh, 3, 2, 1, 1)
        self.pBackspace2 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBackspace2.sizePolicy().hasHeightForWidth())
        self.pBackspace2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pBackspace2.setFont(font)
        self.pBackspace2.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pBackspace2.setObjectName("pBackspace2")
        self.gridLayout.addWidget(self.pBackspace2, 0, 2, 1, 2)
        self.pExponent = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pExponent.sizePolicy().hasHeightForWidth())
        self.pExponent.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pExponent.setFont(font)
        self.pExponent.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pExponent.setObjectName("pExponent")
        self.gridLayout.addWidget(self.pExponent, 3, 3, 1, 1)
        self.pCeil = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pCeil.sizePolicy().hasHeightForWidth())
        self.pCeil.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pCeil.setFont(font)
        self.pCeil.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pCeil.setObjectName("pCeil")
        self.gridLayout.addWidget(self.pCeil, 5, 3, 1, 1)
        self.pCos = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pCos.sizePolicy().hasHeightForWidth())
        self.pCos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pCos.setFont(font)
        self.pCos.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pCos.setObjectName("pCos")
        self.gridLayout.addWidget(self.pCos, 1, 1, 1, 1)
        self.pExponential = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pExponential.sizePolicy().hasHeightForWidth())
        self.pExponential.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pExponential.setFont(font)
        self.pExponential.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pExponential.setObjectName("pExponential")
        self.gridLayout.addWidget(self.pExponential, 2, 3, 1, 1)
        self.pSin = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pSin.sizePolicy().hasHeightForWidth())
        self.pSin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pSin.setFont(font)
        self.pSin.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pSin.setObjectName("pSin")
        self.gridLayout.addWidget(self.pSin, 1, 0, 1, 1)
        self.pSqrt = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pSqrt.sizePolicy().hasHeightForWidth())
        self.pSqrt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pSqrt.setFont(font)
        self.pSqrt.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pSqrt.setObjectName("pSqrt")
        self.gridLayout.addWidget(self.pSqrt, 4, 2, 1, 1)
        self.pACos = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pACos.sizePolicy().hasHeightForWidth())
        self.pACos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pACos.setFont(font)
        self.pACos.setStyleSheet("background-color: rgb(107, 255, 107);")
        self.pACos.setObjectName("pACos")
        self.gridLayout.addWidget(self.pACos, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Calculator", None, QtGui.QApplication.UnicodeUTF8))
        self.pClear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.pBackspace.setText(QtGui.QApplication.translate("MainWindow", "Backspace", None, QtGui.QApplication.UnicodeUTF8))
        self.p2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.p1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.p3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.pSubstract.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.p9.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.p4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.p7.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.p5.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.pDivision.setText(QtGui.QApplication.translate("MainWindow", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.pMultiply.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.pDot.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.pAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.p0.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.pEqualTo.setText(QtGui.QApplication.translate("MainWindow", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.p8.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.p6.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.pOpenParenthesis2.setText(QtGui.QApplication.translate("MainWindow", "(", None, QtGui.QApplication.UnicodeUTF8))
        self.pCloseParenthesis2.setText(QtGui.QApplication.translate("MainWindow", ")", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Standard), QtGui.QApplication.translate("MainWindow", "Standard", None, QtGui.QApplication.UnicodeUTF8))
        self.pATan.setText(QtGui.QApplication.translate("MainWindow", "atan", None, QtGui.QApplication.UnicodeUTF8))
        self.pFact.setText(QtGui.QApplication.translate("MainWindow", "fact", None, QtGui.QApplication.UnicodeUTF8))
        self.pTan.setText(QtGui.QApplication.translate("MainWindow", "tan", None, QtGui.QApplication.UnicodeUTF8))
        self.pCloseParenthesis.setText(QtGui.QApplication.translate("MainWindow", ")", None, QtGui.QApplication.UnicodeUTF8))
        self.pCosh.setText(QtGui.QApplication.translate("MainWindow", "cosh", None, QtGui.QApplication.UnicodeUTF8))
        self.pNaturalLog.setText(QtGui.QApplication.translate("MainWindow", "ln", None, QtGui.QApplication.UnicodeUTF8))
        self.pASin.setText(QtGui.QApplication.translate("MainWindow", "asin", None, QtGui.QApplication.UnicodeUTF8))
        self.pFloor.setText(QtGui.QApplication.translate("MainWindow", "floor", None, QtGui.QApplication.UnicodeUTF8))
        self.pEqualTo2.setText(QtGui.QApplication.translate("MainWindow", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.pLog.setText(QtGui.QApplication.translate("MainWindow", "log", None, QtGui.QApplication.UnicodeUTF8))
        self.pPI.setText(QtGui.QApplication.translate("MainWindow", "pi", None, QtGui.QApplication.UnicodeUTF8))
        self.pClear2.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.pSinh.setText(QtGui.QApplication.translate("MainWindow", "sinh", None, QtGui.QApplication.UnicodeUTF8))
        self.pMod.setText(QtGui.QApplication.translate("MainWindow", "mod", None, QtGui.QApplication.UnicodeUTF8))
        self.pRem.setText(QtGui.QApplication.translate("MainWindow", ",", None, QtGui.QApplication.UnicodeUTF8))
        self.pOpenParenthesis.setText(QtGui.QApplication.translate("MainWindow", "(", None, QtGui.QApplication.UnicodeUTF8))
        self.pAbs.setText(QtGui.QApplication.translate("MainWindow", "abs", None, QtGui.QApplication.UnicodeUTF8))
        self.pTanh.setText(QtGui.QApplication.translate("MainWindow", "tanh", None, QtGui.QApplication.UnicodeUTF8))
        self.pBackspace2.setText(QtGui.QApplication.translate("MainWindow", "Backspace", None, QtGui.QApplication.UnicodeUTF8))
        self.pExponent.setText(QtGui.QApplication.translate("MainWindow", "^", None, QtGui.QApplication.UnicodeUTF8))
        self.pCeil.setText(QtGui.QApplication.translate("MainWindow", "ceil", None, QtGui.QApplication.UnicodeUTF8))
        self.pCos.setText(QtGui.QApplication.translate("MainWindow", "cos", None, QtGui.QApplication.UnicodeUTF8))
        self.pExponential.setText(QtGui.QApplication.translate("MainWindow", "e", None, QtGui.QApplication.UnicodeUTF8))
        self.pSin.setText(QtGui.QApplication.translate("MainWindow", "sin", None, QtGui.QApplication.UnicodeUTF8))
        self.pSqrt.setText(QtGui.QApplication.translate("MainWindow", "sqrt", None, QtGui.QApplication.UnicodeUTF8))
        self.pACos.setText(QtGui.QApplication.translate("MainWindow", "acos", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Scientific", None, QtGui.QApplication.UnicodeUTF8))

